## basic function numpy

In [1]:
import numpy as np

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(10,)

In [5]:
arr[5]

5

In [6]:
arr[7] = 100
arr

array([  0,   1,   2,   3,   4,   5,   6, 100,   8,   9])

In [7]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
arr1[1][3]

9

In [9]:
arr1.shape

(2, 5)

In [10]:
arr1[1][-1]

10

In [11]:
arr2 = np.array(["china", "india", "usa", "mexico"])
arr2

array(['china', 'india', 'usa', 'mexico'], dtype='<U6')

In [12]:
arr3 = np.arange(0,21,2)
arr3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [13]:
arr4 = np.linspace(0,10,20)
arr4

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [14]:
arr5  = np.random.rand(10)
arr5

array([0.71285711, 0.87894509, 0.44136566, 0.24339614, 0.25038   ,
       0.08934955, 0.45426931, 0.67878623, 0.84723968, 0.66443194])

In [15]:
arr6 = np.random.rand(3,4)
arr6

array([[0.52299711, 0.8068219 , 0.4386056 , 0.95593799],
       [0.94015529, 0.96895387, 0.13396174, 0.87013447],
       [0.61965562, 0.84571355, 0.01827796, 0.95062461]])

In [16]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((10,10,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
  

In [19]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
arr = [0,1,2,3,4,5,6,7,8,9,10]
np.repeat(arr,3)

array([ 0,  0,  0,  1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,
        5,  6,  6,  6,  7,  7,  7,  8,  8,  8,  9,  9,  9, 10, 10, 10])

In [21]:
arr = np.tile(arr,3)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr  = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
arr = np.diag([1,2,3,4,5,6])
arr

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [24]:
arr = np.random.rand(5,5)
arr

array([[0.02804587, 0.34725852, 0.5788284 , 0.66502165, 0.26194836],
       [0.29427414, 0.99450762, 0.86672719, 0.71900318, 0.1040274 ],
       [0.8423898 , 0.69559011, 0.98293775, 0.26356711, 0.37091897],
       [0.46629621, 0.71776363, 0.01414631, 0.12520262, 0.95926539],
       [0.96892255, 0.63528589, 0.14727732, 0.76896874, 0.82415545]])

In [25]:
np.diag(arr)

array([0.02804587, 0.99450762, 0.98293775, 0.12520262, 0.82415545])

In [26]:
arr.size

25

In [27]:
arr.shape

(5, 5)

In [28]:
arr = np.random.randint(-10,10,4)
arr

array([ 9,  7,  5, -8])

In [29]:
arr+10

array([19, 17, 15,  2])

In [30]:
arr-5

array([  4,   2,   0, -13])

In [31]:
arr/2

array([ 4.5,  3.5,  2.5, -4. ])

In [32]:
np.exp(arr)

array([8.10308393e+03, 1.09663316e+03, 1.48413159e+02, 3.35462628e-04])

In [33]:
np.log(arr)

C:\Users\Administrador\AppData\Local\Temp\ipykernel_4612\3120950136.py:1: RuntimeWarning: invalid value encountered in log
  np.log(arr)


array([2.19722458, 1.94591015, 1.60943791,        nan])

In [34]:
np.sin(arr)

array([ 0.41211849,  0.6569866 , -0.95892427, -0.98935825])

In [35]:
np.cos(arr)

array([-0.91113026,  0.75390225,  0.28366219, -0.14550003])

In [36]:
np.tan(arr)

array([-0.45231566,  0.87144798, -3.38051501,  6.79971146])

In [37]:
arr = np.random.rand(5,5)
arr

array([[0.56731493, 0.97577175, 0.63757143, 0.15400879, 0.11208092],
       [0.77206023, 0.51040646, 0.99607402, 0.3218025 , 0.04040912],
       [0.79773444, 0.07162143, 0.61622296, 0.7156729 , 0.01759301],
       [0.7479116 , 0.6879914 , 0.92386353, 0.47039651, 0.85108948],
       [0.48149416, 0.81206385, 0.38159794, 0.07093279, 0.2978264 ]])

In [38]:
np.sum(arr, axis=1) #row

array([2.44674781, 2.64075233, 2.21884474, 3.68125253, 2.04391514])

In [39]:
np.sum(arr, axis=0) #col

array([3.36651535, 3.0578549 , 3.55532987, 1.7328135 , 1.31899893])

In [40]:
np.min(arr)

0.017593009904243728

In [41]:
np.max(arr)

0.9960740178904869

In [42]:
np.min(arr, axis=1)

array([0.11208092, 0.04040912, 0.01759301, 0.47039651, 0.07093279])

In [43]:
np.max(arr, axis=0)

array([0.79773444, 0.97577175, 0.99607402, 0.7156729 , 0.85108948])

In [44]:
np.mean(arr)

0.5212605020749326

In [45]:
np.mean(arr, axis=1)

array([0.48934956, 0.52815047, 0.44376895, 0.73625051, 0.40878303])

In [46]:
np.mean(arr, axis=0)

array([0.67330307, 0.61157098, 0.71106597, 0.3465627 , 0.26379979])

In [47]:
np.var(arr)

0.09496448624500163

In [48]:
np.std(arr)

0.308163083845229

In [49]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

In [50]:
arr[:3]

array([0, 1, 2])

In [51]:
arr[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [52]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr[1:,2:3]

array([[8]])

In [53]:
arr[0:,2:3]

array([[3],
       [8]])

In [54]:
np.sort(arr)

array([[1, 2, 3, 4, 5],
       [0, 6, 7, 8, 9]])

In [55]:
arr = np.random.rand(5,5)
arr

array([[1.29993127e-01, 5.06509094e-01, 4.22547986e-01, 4.98726787e-01,
        2.88037989e-01],
       [4.83565429e-01, 6.48405166e-01, 8.38744294e-01, 2.42050470e-01,
        3.54987997e-01],
       [2.67135450e-01, 6.50800423e-01, 7.96508029e-01, 6.70649569e-01,
        9.89133884e-01],
       [9.60577002e-04, 2.80620838e-02, 7.50643236e-01, 5.59378672e-01,
        2.74347870e-01],
       [6.31714331e-01, 3.37519162e-01, 6.70619641e-01, 9.79533930e-01,
        6.57418670e-01]])

In [56]:
np.sort(arr, axis=0)

array([[9.60577002e-04, 2.80620838e-02, 4.22547986e-01, 2.42050470e-01,
        2.74347870e-01],
       [1.29993127e-01, 3.37519162e-01, 6.70619641e-01, 4.98726787e-01,
        2.88037989e-01],
       [2.67135450e-01, 5.06509094e-01, 7.50643236e-01, 5.59378672e-01,
        3.54987997e-01],
       [4.83565429e-01, 6.48405166e-01, 7.96508029e-01, 6.70649569e-01,
        6.57418670e-01],
       [6.31714331e-01, 6.50800423e-01, 8.38744294e-01, 9.79533930e-01,
        9.89133884e-01]])

In [57]:
arr[:3,:4]

array([[0.12999313, 0.50650909, 0.42254799, 0.49872679],
       [0.48356543, 0.64840517, 0.83874429, 0.24205047],
       [0.26713545, 0.65080042, 0.79650803, 0.67064957]])

In [58]:
arr[:3,:4].transpose()

array([[0.12999313, 0.48356543, 0.26713545],
       [0.50650909, 0.64840517, 0.65080042],
       [0.42254799, 0.83874429, 0.79650803],
       [0.49872679, 0.24205047, 0.67064957]])

In [59]:
arr.flatten()

array([1.29993127e-01, 5.06509094e-01, 4.22547986e-01, 4.98726787e-01,
       2.88037989e-01, 4.83565429e-01, 6.48405166e-01, 8.38744294e-01,
       2.42050470e-01, 3.54987997e-01, 2.67135450e-01, 6.50800423e-01,
       7.96508029e-01, 6.70649569e-01, 9.89133884e-01, 9.60577002e-04,
       2.80620838e-02, 7.50643236e-01, 5.59378672e-01, 2.74347870e-01,
       6.31714331e-01, 3.37519162e-01, 6.70619641e-01, 9.79533930e-01,
       6.57418670e-01])

In [60]:
arr = np.array([4,5,6,7,8])
arr

array([4, 5, 6, 7, 8])

In [61]:
arr = np.append(arr, 8)
arr

array([4, 5, 6, 7, 8, 8])

In [62]:
arr1 = np.insert(arr, 2, 100)
arr1

array([  4,   5, 100,   6,   7,   8,   8])

In [63]:
arr2 = np.insert(arr1, 0, [1,2,3,4,5])
arr2

array([  1,   2,   3,   4,   5,   4,   5, 100,   6,   7,   8,   8])

In [64]:
arr3 = np.delete(arr2, [0,-1])
arr3

array([  2,   3,   4,   5,   4,   5, 100,   6,   7,   8])

In [65]:
arrC = arr3.copy()
arrC

array([  2,   3,   4,   5,   4,   5, 100,   6,   7,   8])

In [66]:
arr1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr2 = np.array([[6,7,8,9,0],[6,7,8,9,0]])

In [67]:
arr_cat = np.concatenate((arr1, arr2))
arr_cat

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [6, 7, 8, 9, 0]])

In [68]:
arr_cat_row = np.concatenate((arr1, arr2), axis = 0)
arr_cat_row 

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [6, 7, 8, 9, 0]])

In [69]:
arr_cat_col = np.concatenate((arr1, arr2), axis = 1)
arr_cat_col 

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 0],
       [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]])

In [70]:
catV = np.vstack((arr1, arr2))
catV

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [6, 7, 8, 9, 0]])

In [71]:
catH = np.hstack((arr1, arr2))
catH

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 0],
       [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]])

In [72]:
arr = np.array([1,2,3,4,5,6,3,6,1,2,4])
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

In [73]:
uniques, counts = np.unique(arr, return_counts=True)

In [74]:
uniques

array([1, 2, 3, 4, 5, 6])

In [75]:
counts

array([2, 2, 2, 2, 1, 2], dtype=int64)

In [76]:
# intersection, differentiation, neither
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [77]:
np.intersect1d(arr1, arr2)

array([3, 4, 5])

In [78]:
np.union1d(arr1, arr2)

array([1, 2, 3, 4, 5, 6, 7])

In [79]:
np.setdiff1d(arr1, arr2)

array([1, 2])

In [80]:
np.setxor1d(arr1, arr2)

array([1, 2, 6, 7])