## basic function numpy

In [1]:
import numpy as np

In [3]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(arr)

numpy.ndarray

In [7]:
arr.shape

(10,)

In [8]:
arr[5]

5

In [10]:
arr[7] = 100
arr

array([  0,   1,   2,   3,   4,   5,   6, 100,   8,   9])

In [11]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
arr1[1][3]

9

In [13]:
arr1.shape

(2, 5)

In [15]:
arr1[1][-1]

10

In [16]:
arr2 = np.array(["china", "india", "usa", "mexico"])
arr2

array(['china', 'india', 'usa', 'mexico'], dtype='<U6')

In [18]:
arr3 = np.arange(0,21,2)
arr3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [19]:
arr4 = np.linspace(0,10,20)
arr4

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [20]:
arr5  = np.random.rand(10)
arr5

array([0.44652182, 0.13873393, 0.19456875, 0.19856532, 0.66357739,
       0.59548468, 0.55694978, 0.47244625, 0.14357   , 0.40947447])

In [21]:
arr6 = np.random.rand(3,4)
arr6

array([[0.17189204, 0.56217819, 0.78306747, 0.42511495],
       [0.89573548, 0.57003899, 0.47772075, 0.79655414],
       [0.97092204, 0.00660625, 0.99005271, 0.01483613]])

In [23]:
np.zeros(10)


array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((10,10,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
  

In [27]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
arr = [0,1,2,3,4,5,6,7,8,9,10]
np.repeat(arr,3)

array([ 0,  0,  0,  1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,
        5,  6,  6,  6,  7,  7,  7,  8,  8,  8,  9,  9,  9, 10, 10, 10])

In [30]:
arr = np.tile(arr,3)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0,
        1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0,  1,
        2,  3,  4,  5,  6,  7,  8,  9, 10,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr  = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
arr = np.diag([1,2,3,4,5,6])
arr

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [34]:
arr = np.random.rand(5,5)
arr

array([[0.97801701, 0.58510284, 0.46589776, 0.44186691, 0.36550035],
       [0.85723959, 0.45992448, 0.66739424, 0.69894046, 0.29448223],
       [0.6209215 , 0.461849  , 0.73352239, 0.64719706, 0.92974556],
       [0.0718515 , 0.29046645, 0.80436536, 0.78933661, 0.20514702],
       [0.66018572, 0.8632601 , 0.88800852, 0.5573378 , 0.12866624]])

In [35]:
np.diag(arr)

array([0.97801701, 0.45992448, 0.73352239, 0.78933661, 0.12866624])

In [36]:
arr.size

25

In [37]:
arr.shape

(5, 5)

In [38]:
arr = np.random.randint(-10,10,4)
arr

array([ -6, -10,   8,   6])

In [39]:
arr+10

array([ 4,  0, 18, 16])

In [40]:
arr-5

array([-11, -15,   3,   1])

In [41]:
arr/2

array([-3., -5.,  4.,  3.])

In [43]:
np.exp(arr)

array([2.47875218e-03, 4.53999298e-05, 2.98095799e+03, 4.03428793e+02])

In [44]:
np.log(arr)

C:\Users\Administrador\AppData\Local\Temp\ipykernel_6060\3120950136.py:1: RuntimeWarning: invalid value encountered in log
  np.log(arr)


array([       nan,        nan, 2.07944154, 1.79175947])

In [45]:
np.sin(arr)

array([ 0.2794155 ,  0.54402111,  0.98935825, -0.2794155 ])

In [46]:
np.cos(arr)

array([ 0.96017029, -0.83907153, -0.14550003,  0.96017029])

In [47]:
np.tan(arr)

array([ 0.29100619, -0.64836083, -6.79971146, -0.29100619])

In [49]:
arr = np.random.rand(5,5)
arr

array([[0.04323498, 0.23628294, 0.06990571, 0.69365412, 0.76368415],
       [0.05247439, 0.94676521, 0.05842454, 0.25861297, 0.23677928],
       [0.97724074, 0.09435127, 0.18464079, 0.89877135, 0.07346383],
       [0.97005859, 0.05640996, 0.61345853, 0.8945302 , 0.65688107],
       [0.21074519, 0.63140354, 0.31267116, 0.34113859, 0.29219588]])

In [50]:
np.sum(arr, axis=1) #row

array([1.80676191, 1.55305639, 2.22846799, 3.19133835, 1.78815436])

In [51]:
np.sum(arr, axis=0) #col

array([2.25375389, 1.96521292, 1.23910073, 3.08670723, 2.02300422])

In [52]:
np.min(arr)

0.043234977635419836

In [53]:
np.max(arr)

0.9772407381696299

In [54]:
np.min(arr, axis=1)

array([0.04323498, 0.05247439, 0.07346383, 0.05640996, 0.21074519])

In [56]:
np.max(arr, axis=0)

array([0.97724074, 0.94676521, 0.61345853, 0.89877135, 0.76368415])

In [57]:
np.mean(arr)

0.4227111599078349

In [58]:
np.mean(arr, axis=1)

array([0.36135238, 0.31061128, 0.4456936 , 0.63826767, 0.35763087])

In [59]:
np.mean(arr, axis=0)

array([0.45075078, 0.39304258, 0.24782015, 0.61734145, 0.40460084])

In [60]:
np.var(arr)

0.11165198425703685

In [63]:
np.std(arr)

0.33414365811284946

In [64]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

In [65]:
arr[:3]

array([0, 1, 2])

In [66]:
arr[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [67]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr[1:,2:3]

array([[8]])

In [72]:
arr[0:,2:3]

array([[3],
       [8]])

In [73]:
np.sort(arr)

array([[1, 2, 3, 4, 5],
       [0, 6, 7, 8, 9]])

In [74]:
arr = np.random.rand(5,5)
arr

array([[0.05761986, 0.61451204, 0.92583259, 0.04816503, 0.27915928],
       [0.74214789, 0.15942525, 0.23917093, 0.65684784, 0.84692386],
       [0.08197369, 0.32075797, 0.06518092, 0.40477096, 0.37388711],
       [0.16868656, 0.35874132, 0.93076608, 0.44922811, 0.10883077],
       [0.98915458, 0.74376861, 0.72977015, 0.27241854, 0.45840839]])

In [76]:
np.sort(arr, axis=0)

array([[0.05761986, 0.15942525, 0.06518092, 0.04816503, 0.10883077],
       [0.08197369, 0.32075797, 0.23917093, 0.27241854, 0.27915928],
       [0.16868656, 0.35874132, 0.72977015, 0.40477096, 0.37388711],
       [0.74214789, 0.61451204, 0.92583259, 0.44922811, 0.45840839],
       [0.98915458, 0.74376861, 0.93076608, 0.65684784, 0.84692386]])

In [77]:
arr[:3,:4]

array([[0.05761986, 0.61451204, 0.92583259, 0.04816503],
       [0.74214789, 0.15942525, 0.23917093, 0.65684784],
       [0.08197369, 0.32075797, 0.06518092, 0.40477096]])

In [78]:
arr[:3,:4].transpose()

array([[0.05761986, 0.74214789, 0.08197369],
       [0.61451204, 0.15942525, 0.32075797],
       [0.92583259, 0.23917093, 0.06518092],
       [0.04816503, 0.65684784, 0.40477096]])

In [79]:
arr.flatten()

array([0.05761986, 0.61451204, 0.92583259, 0.04816503, 0.27915928,
       0.74214789, 0.15942525, 0.23917093, 0.65684784, 0.84692386,
       0.08197369, 0.32075797, 0.06518092, 0.40477096, 0.37388711,
       0.16868656, 0.35874132, 0.93076608, 0.44922811, 0.10883077,
       0.98915458, 0.74376861, 0.72977015, 0.27241854, 0.45840839])

In [80]:
arr = np.array([4,5,6,7,8])
arr

array([4, 5, 6, 7, 8])

In [81]:
arr = np.append(arr, 8)
arr

array([4, 5, 6, 7, 8, 8])

In [84]:
arr1 = np.insert(arr, 2, 100)
arr1

array([  4,   5, 100,   6,   7,   8,   8])

In [85]:
arr2 = np.insert(arr1, 0, [1,2,3,4,5])
arr2

array([  1,   2,   3,   4,   5,   4,   5, 100,   6,   7,   8,   8])

In [94]:
arr3 = np.delete(arr2, [0,-1])
arr3

array([  2,   3,   4,   5,   4,   5, 100,   6,   7,   8])

In [95]:
arrC = arr3.copy()
arrC

array([  2,   3,   4,   5,   4,   5, 100,   6,   7,   8])

In [96]:
arr1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr2 = np.array([[6,7,8,9,0],[6,7,8,9,0]])

In [98]:
arr_cat = np.concatenate((arr1, arr2))
arr_cat

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [6, 7, 8, 9, 0]])

In [100]:
arr_cat_row = np.concatenate((arr1, arr2), axis = 0)
arr_cat_row 

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [6, 7, 8, 9, 0]])

In [101]:
arr_cat_col = np.concatenate((arr1, arr2), axis = 1)
arr_cat_col 

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 0],
       [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]])

In [102]:
catV = np.vstack((arr1, arr2))
catV

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [6, 7, 8, 9, 0]])

In [103]:
catH = np.hstack((arr1, arr2))
catH

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 0],
       [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]])

In [104]:
arr = np.array([1,2,3,4,5,6,3,6,1,2,4])
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

In [105]:
uniques, counts = np.unique(arr, return_counts=True)

In [106]:
uniques

array([1, 2, 3, 4, 5, 6])

In [107]:
counts

array([2, 2, 2, 2, 1, 2], dtype=int64)